organizations:
  # The organizations field defines the topology of the managed teams and services across 
  # one or more Konnect Organizations. This allows the orchestrator to
  # manage consistent resource names and configurations
  
  # This key is arbitrary, but it's recommended to relate to 
  # the organization name within Konnect
  KongAirlines:
  
    # This configures how the orchestrator authenticates to Konnect APIs.
    # API calls are scoped to organizations via the access-token used,
    # thus, we don't need to track the org ID here.
    # The access-token field supports a file, environment variable, or literal string type.
    access-token:
      type: file
      value: $HOME/.konnect/20250214-Konnect-Orchestrator.spat
      # ---
      # type: env
      # value: KONNECT_ACCESS_TOKEN
      # ---
      # type: literal # not recommended to prevent accidental exposure
      # value: pat_ajbjdkfjhfhijajaj
  
    # This defines the organization's Konnect _user_ authentication configuration,
    # including IdP configurations and team mappings.
    # It is recommended to use a single authentication method, however, 
    # Konnect supports the ability to combine built-in authentication with either OIDC or SAML based SSO. 
    # Combining both OIDC and SAML based SSO is not supported. Keep built-in authentication enabled 
    # while you are testing IdP authentication and only disable it after successfully testing your SSO configuration.
    authorization:
      built-in:
        enabled: true
      oidc:
        enabled: true
        login-path: kongairlines
        issuer: https://dev-26696402.okta.com/oauth2/default
        client-id: 0oamj7tntcMapIsET5d7
        client-secret:
          type: file
          value: $HOME/.konnect/kongairlines-oidc-client-secret.txt
        claim-mappings:
          email: email
          name: name
          groups: groups
        scopes:
          - openid
          - email
          - profile
      saml:
        enabled: false
        login-path: kongairlines_saml
        idp-metadata-url: https://dev-26696402.okta.com/app/exkmoj7cryENs4tDa5d7/sso/saml/metadata
      team-mappings:
        built-in:
          enabled: true
        idp:
          enabled: true
          mappings:
            "Organization Admin": 
            - "platform"
            - "api-admins"
      
    environments:
      dev: # an environment name
        # `type` is required and can be either: `DEV` or `PROD`
        #   These values are well known to the orchestrator and are used to determine the 
        #   policies applied to resources
        type: DEV
        # `region` is required and must equal one of the Konnect supported region strings
        region: us
      prd:
        type: PROD
        region: us
  
