platform:
  git:
    remote: https://github.com/KongAirlines/platform.git 
    author:
      name: "Konnect Orchestrator"
      email: "ko@konghq.com"
    github:
      token:
        type: file
        value: $HOME/.github/20250228-KongAirlines-ko.pat
