name: Konnect - koctl apply
on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "konnect/teams.yaml"
            - "konnect/organizations.yaml"
jobs:
    koctl-apply:
        name: Apply configuration to Konnect
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup koctl
              uses: jaxxstorm/action-install-gh-release@v2.0.0
              with:
                repo: Kong/konnect-orchestrator
                tag: v0.7.0
            - name: Check secret exists
              env:
                MY_SECRET: ${{ secrets.KONGAIRLINES_KONNECT_TOKEN }}
              run: |
                if [ -z "$MY_SECRET" ]; then
                  echo "Secret is empty or missing!"
                  exit 1
                fi
                 # Show a partial (first 4 and last 4 chars)
                FIRST4=${MY_SECRET:0:4}
                LAST4=${MY_SECRET: -4}
                LEN=${#MY_SECRET}

                echo "Secret is set (length: $LEN)"
                echo "Start: $FIRST4**** End: ****$LAST4"
            - name: Run koctl apply
              id: koctl-apply
              env:
                GITHUB_TOKEN: ${{ secrets.KONNECT_ORCHESTRATOR_GITHUB_TOKEN }}
                GITHUB_REPO_URL: "https://github.com/${{ github.repository }}"
                KONGAIRLINES_KONNECT_TOKEN: ${{secrets.KONGAIRLINES_KONNECT_TOKEN}}
              run: "koctl apply \n"
