name: decK Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    paths:
      - "konnect/**/kong.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Collect modified decK files
        run: |
          CHANGED_DECK_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'deck.yaml' || true)
          echo "changed_deck_files=$CHANGED_DECK_FILES" >> $GITHUB_ENV

      - name: Lint decK files 
        if: ${{ env.changed_deck_files != '' }}
        run: |
          for FILE in "$changed_deck_files"; do
            deck lint -f ${{ github.workspace }}/konnect/**/kong.yaml
          done
