name: Kong GW Config Conformance

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited, ready_for_review ]
    branches: 
      - convert-specs-to-deck # This is the branch where the spec-to-deck.yaml workflow will push
    paths:
      - "konnect/**/kong.yaml"

jobs:
  lint-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Collect modified decK files
        run: |
          CHANGED_DECK_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep 'kong.yaml')
          CHANGED_DECK_FILES=$(echo $CHANGED_DECK_FILES | tr '\n' ' ')
          echo "changed_deck_files=$CHANGED_DECK_FILES" >> $GITHUB_ENV

      - name: Lint decK files 
        if: ${{ env.changed_deck_files != '' }}
        run: |
          for FILE in $changed_deck_files; do
            deck file lint -s "$FILE" konnect/deck-file-rules.yaml
          done
