name: Spec To decK

on:
  push:
    branches:
      - main
      - test-actions
    paths:
      - "konnect/**/openapi.yaml"

jobs:
  convert-specs-to-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect modified Spec files
        id: changed_specs
        run: |
          echo "event: ${{ github.event_name }}"
          echo "sha: ${{ github.sha }}"
          echo "before: ${{ github.event.before }}"
          CHANGED_SPEC_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'openapi.yaml' || true)
          echo "changed_spec_files=$CHANGED_SPEC_FILES" >> $GITHUB_ENV
          echo "$CHANGED_SPEC_FILES"

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Process changed Spec files
        if: ${{ env.changed_spec_files != '' }}
        run: |
          for FILE in $CHANGED_SPEC_FILES; do
            OUTPUT_FILE=$(dirname "$FILE")/kong.yaml
            deck file openapi2kong $FILE -o $OUTPUT_FILE 
            echo $OUTPUT_FILE
            cat $OUTPUT_FILE
          done


