name: Convert API Spec -> Kong GW Config

on:
  push:
    branches:
      - main
      - test-actions
    paths:
      - "konnect/**/openapi.yaml"

jobs:
  convert-specs-to-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect modified Spec files
        run: |
          # Find changed openapi.yaml files and join them into a space-separated string
          CHANGED_SPEC_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'openapi.yaml' || true)
          CHANGED_SPEC_FILES=$(echo $CHANGED_SPEC_FILES | tr '\n' ' ')
          if [[ -z "$CHANGED_SPEC_FILES" ]]; then
            echo "No modified openapi.yaml files found. Exiting workflow."
            exit 0
          fi
          echo "changed_spec_files=${CHANGED_SPEC_FILES}" >> $GITHUB_ENV
        shell: bash

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Convert Spec files to Kong Gateway Configuration
        if: ${{ env.changed_spec_files != '' }}
        run: |
          for FILE in ${{ env.changed_spec_files }}; do
            OUTPUT_FILE=$(dirname "$FILE")/kong.yaml
            deck file openapi2kong -s "$FILE" -o "$OUTPUT_FILE"
            echo "Converted $FILE to $OUTPUT_FILE"
          done

      - name: Create PR for changed Kong Gateway Configuration
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[Auto] Kong GW Configuration change"
          commit-message: "Updates Kong Gateway Configuration based on API Spec changes" 
          body: |
            This PR was automatically generated by the 'Convert API Spec -> Kong GW Config' workflow.
          branch: convert-specs-to-deck
