name: Spec To decK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test-actions
    paths:
      - "konnect/**/openapi.yaml"

jobs:
  convert-specs-to-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect modified OAS files
        id: changed_specs
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.sha }}
          echo ${{ github.event.base_ref }}
          echo ${{ github.event.before }}
          echo ${{ github.event.pull_request.base.ref }}
          echo ${{ github.event.pull_request.base.sha }}
          git diff ${{github.event.before}} ${{github.sha}}

