name: Spec To decK

on:
  push:
    branches:
      - main
      - test-actions
    paths:
      - "konnect/**/openapi.yaml"

jobs:
  convert-specs-to-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect modified Spec files
        run: |
          CHANGED_SPEC_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'openapi.yaml' || true)
          echo "changed_spec_files=$CHANGED_SPEC_FILES" >> $GITHUB_ENV

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Convert Spec files to Kong Gateway Configuration
        if: ${{ env.changed_spec_files != '' }}
        run: |
          for FILE in "$changed_spec_files"; do
            OUTPUT_FILE=$(dirname "$FILE")/kong.yaml
            deck file openapi2kong -s "$FILE" -o "$OUTPUT_FILE"
            echo "Converted $FILE to $OUTPUT_FILE"
          done

      - name: Create PR for changed Kong Gateway Configuration
        uses: peter-evans/create-pull-request@v5
        with:
          title: Stage Kong Gateway Configuration
