name: Konnect - OpenAPI to Kong 

on:
  push:
    branches:
      - main
      - test-actions
    paths:
      - "konnect/**/openapi.yaml"

jobs:
  convert-specs-to-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect modified OAS files
        id: changed-oas-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            konnect/**/openapi.yaml

      - name: Setup deck
        if: steps.changed-oas-files.outputs.any_changed == 'true' 
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'
          wrapper: false

      - name: Convert Spec files to Kong Gateway Configuration
        if: steps.changed-oas-files.outputs.any_changed == 'true' 
        env:
          CHANGED_OAS_FILES: ${{ steps.changed-oas-files.outputs.all_changed_files }}
        run: |
          for FILE in ${CHANGED_OAS_FILES}; do
            OUTPUT_FILE=$(dirname "$FILE")/kong-from-oas.yaml
            deck file openapi2kong -s "$FILE" -o "$OUTPUT_FILE"
            echo "Generated $OUTPUT_FILE from $FILE"
          done

      - name: Create PR for changed Kong Gateway Configuration
        if: steps.changed-oas-files.outputs.any_changed == 'true' 
        uses: peter-evans/create-pull-request@v5
        with:
          title: "[Konnect] Kong GW Configuration change"
          commit-message: "Updates Kong Gateway Configuration based on API Spec changes" 
          body: |
            This PR was automatically generated by the 'Konnect - OpenAPI to Kong' workflow.
          branch: konnect-convert-specs-to-deck
